// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Big = require("../src/Big.bs.js");
var BigJs = require("big.js");

var a = BigJs.Big(201.57512);

var b = BigJs.Big(1);

console.log(a.toFixed(2));

console.log(Big.Operators.$star$dot(a, b));

exports.a = a;
exports.b = b;
/* a Not a pure module */
