// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var BigJs = require("big.js");

var a = BigJs.Big(201.57512);

var b = BigJs.Big(1);

var c = a.plus(b);

console.log(c.toFixed(2));

exports.a = a;
exports.b = b;
exports.c = c;
/* a Not a pure module */
