// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Big = require("../src/Big.bs.js");

var decimal = Big.big(201.57512);

console.log(decimal);

console.log(Big.toFixed(decimal, 2));

console.log(Big.Operators.$plus$dot(Big.big(0.1), Big.big(0.2)));

console.log(Big.Operators.$star$dot(Big.big(2.5), Big.big(0)));

exports.decimal = decimal;
/* decimal Not a pure module */
