// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


function $plus$dot(a, b) {
  return a.plus(b);
}

function $star$dot(a, b) {
  return a.times(b);
}

function $neg$dot(a, b) {
  return a.minus(b);
}

function $slash$dot(a, b) {
  return a.div(b);
}

var Operators = {
  $plus$dot: $plus$dot,
  $star$dot: $star$dot,
  $neg$dot: $neg$dot,
  $slash$dot: $slash$dot
};

exports.Operators = Operators;
/* No side effect */
