# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: rescript-big-test-suite

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setting up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 13

      - name: Install
        run: |
          echo "scope=wino" >> .npmrc
          echo "@wino:registry=https://registry.npmjs.org/" >> .npmrc
          echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> .npmrc
          yarn
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Build
        run: yarn build

      - name: Test
        run: yarn test
